server:
  port: 8086
hm:
  db:
    database: hm-pay
  swagger:
    title: "商城支付服务接口文档"
    package: com.hmall.pay.controller
spring:
  rabbitmq:
    host: 192.168.157.128
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
